apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-sample
  namespace: minikube
  labels:
    app: php-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-hello-sample
  template:
    metadata:
      labels:
        app: php-hello-sample
    spec:
      containers:
        - name: php-hello-sample
          image: ausaf0909/php-sample:main-a4d3062078165daf3b57c5a3b894998d2b51b182
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
