
apiVersion: v1
kind: Service
metadata:
  name: php-sample
  namespace: minikube
spec:
  selector:
    app: php-hello-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: NodePort
