
name: Build, Push, and Deploy




on:

  push:

    branches:

      - main




jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

      

    steps:

      - name: Checkout code

        uses: actions/checkout@v2




      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v1




      - uses: actions/checkout@v2

      - name: Set env

        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  

 

      - name: Build Docker image

        run: |

          docker buildx create --use

          docker buildx inspect default --bootstrap

          docker buildx build --file Dockerfile -t ausaf0909/php-sample:$GITHUB_REF_NAME-$GITHUB_SHA --load .





      - name: Push Docker image to Docker Hub

        run: |

          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ausaf0909 --password-stdin

          docker push ausaf0909/php-sample:$GITHUB_REF_NAME-$GITHUB_SHA



      - name: Update manifest file

        run: |

          git config user.name "$GITHUB_ACTOR"

          git config user.email "$GITHUB_ACTOR@gmail.com"

          yq eval '.spec.template.spec.containers[0].image = "ausaf0909/php-sample:${{ env.GITHUB_BRANCH }}"' -i Deployment/deployment.yaml



          git pull

          git add .

                 

          git commit -m "updating newer image"

          git push --set-upstream origin main


          
